export default [
  {
    name: 'Urban Detox for Digital Village',
    description: 'This piece is commissioned by #DigitalArtMonth NYC. The Digital Art Month is a creative celebration of digital and new media art kicking off October 1, 2020, in New York.',
    css: 'linear-gradient(to top, #fff1eb 0%, #ace0f9 100%)',
    img: '/img/URBAN_DETOX.png',
    gifImg: '/gifs/URBAN_DETOX.gif',
    alt: 'Urban Detox AR world instagram filter',
    link: 'https://www.instagram.com/ar/765051940995275/',
  },
  {
    name: 'Milkyway X Celine',
    description: 'Collab with Celine Bernaerts',
    css: 'linear-gradient(to top, #d299c2 0%, #fef9d7 100%)',
    img: '/img/CELINE_BERNAERTS.png',
    gifImg: '/gifs/CELINE_BERNAERTS.gif',
    alt: 'milkyway celine bernaerts AR instagram filter',
    link: 'https://www.instagram.com/ar/1138646083274087/',
  },
  {
    name: 'SISI CHANDELIER',
    description: 'description',
    css: 'linear-gradient(to top, #ebc0fd 0%, #d9ded8 100%)',
    img: '/img/SISI_JOHANNA.png',
    gifImg: '/gifs/SISI_JOHANNA.gif',
    alt: 'sisi chandelier AR instagram filter',
    link: 'https://www.instagram.com/ar/123833942995144/',
  },
  {
    name: 'LAYDI CO 💝',
    description: 'description',
    css: 'linear-gradient(to top, #5ee7df 0%, #b490ca 100%)',
    img: '/img/LAYDI_CO.png',
    gifImg: '/gifs/LAYDI_CO.gif',
    alt: 'Laydi CO necklace AR instagram filter',
    link: 'https://www.instagram.com/ar/888489641709371/',
  },
  {
    name: 'La Medusa',
    description: "It has been an honour to create La Medusa effect for the SS21 collection of versace 🐡🐋🐟🦑  \n Thank you albertocarlocafaro for this wonderful collaboration! 🦀 🔥 Try it on versace\‘s profile!",
    css: 'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)',
    img: '/img/Versace.png',
    gifImg: '/gifs/Versace.gif',
    alt: 'versace la medusa AR instagram filter',
    link: '/',
  },
  {
    name: 'DigitalVillage with Allan Gregorio',
    description: "Jardin Digital! 💙 Amazing collab with @hrhevelynmora and @allangregorio for @digitalvillage.io 💙 \n What does the future of digital beauty and fashion mean for you",
    css: 'linear-gradient(120deg, #e0c3fc 0%, #8ec5fc 100%)',
    img: '/img/Digital_Village.png',
    gifImg: '/gifs/Digital_Village.gif',
    alt: 'Digital Village AR instagram filter',
    link: 'https://www.instagram.com/ar/2735153853402107/',
  },
  {
    name: 'Sofishticated',
    description: '#fdfbfb → #ebedee',
    css: 'linear-gradient(-225deg, #E3FDF5 0%, #FFE6FA 100%)',
    img: '/img/SOFISHTICATED.png',
    gifImg: '/gifs/SOFISHTICATED.gif',
    alt: 'sofishsticated coral reef AR instagram filter',
    link: 'https://www.instagram.com/ar/904627139977927/',
  },
  
  {
    name: 'Lilly X ya.molli',
    description: 'description',
    css: 'linear-gradient(120deg, #f6d365 0%, #fda085 100%)',
    img: '/img/LILLY_Ya_Molli.png',
    gifImg: '/gifs/LILLY_Ya_Molli.gif',
    alt: 'lilly AR instagram filter',
    link: 'https://www.instagram.com/ar/138283638167498/',
  },
  {
    name: 'VOGUE',
    description: 'description',
    css: 'linear-gradient(to top, #a8edea 0%, #fed6e3 100%)',
    img: '/img/VOGUE.png',
    gifImg: '/gifs/VOGUE.gif',
    alt: 'vogue AR instagram filter',
    link: 'https://www.instagram.com/ar/728255677794773/',
  },
  {
    name: 'Lancome: Happiness Crown',
    description: 'description',
    css: 'linear-gradient(to top, #96fbc4 0%, #f9f586 100%)',
    img: '/img/Lancome.png',
    gifImg: '/gifs/Lancome.gif',
    alt: 'Lancome Rose Crown AR instagram filter',
    link: '/',
  },
  {
    name: 'Hello 2021',
    description: ' description',
    css: 'linear-gradient(-225deg, #FFFEFF 0%, #D7FFFE 100%)',
    img: '/img/HELLO21.png',
    gifImg: '/gifs/HELLO21.gif',
    alt: 'hello 2021 new years AR instagram filter',
    link: '/',
  },
  {
    name: 'Loreal 2021',
    description: 'description',
    css: 'linear-gradient(to top, #c1dfc4 0%, #deecdd 100%)',
    img: '/img/Loreal.png',
    gifImg: '/gifs/Loreal.gif',
    alt: 'loreal makeup AR instagram filter',
    link: '/',
  },
  {
    name: 'MILK Makeup',
    description: ' description',
    css: 'linear-gradient(-20deg, #ddd6f3 0%, #faaca8 100%, #faaca8 100%)',
    img: '/img/MILK_MAKEUP.png',
    gifImg: '/gifs/MILK_MAKEUP.gif',
    alt: 'milk makeup AR instagram filter',
    link: 'https://www.instagram.com/ar/549493535734936/',
  },
  {
    name: 'Medusa',
    description: 'description',
    css: 'linear-gradient(120deg, #f093fb 0%, #f5576c 100%)',
    img: '/img/MEDUSA.png',
    gifImg: '/gifs/MEDUSA.gif',
    alt: 'medusa AR instagram filter',
    link: 'https://www.instagram.com/ar/2964667820314254/',
  },
  {
    name: 'JUICY',
    description: 'description',
    css: 'linear-gradient(to top, #a8edea 0%, #fed6e3 100%)',
    img: '/img/JUICY.png',
    gifImg: '/gifs/JUICY.gif',
    alt: 'juicy AR instagram filter',
    link: 'https://www.instagram.com/ar/332085664886870/',
  },
  {
    name: 'Dandelion',
    description: 'description',
    css: 'linear-gradient(to top, #a8edea 0%, #fed6e3 100%)',
    img: '/img/DANDELION.png',
    gifImg: '/gifs/DANDELION.gif',
    alt: 'dandelion AR instagram filter',
    link: 'https://www.instagram.com/ar/624854895110155/',
  },
  {
    name: 'Catwoman',
    description: 'description',
    css: 'linear-gradient(to top, #a8edea 0%, #fed6e3 100%)',
    img: '/img/CATWOMAN.png',
    gifImg: '/gifs/CATWOMAN.gif',
    alt: 'catwoman AR instagram filter',
    link: 'https://www.instagram.com/ar/144207790647520/',
  },
  {
    name: 'Bread King',
    description: 'description',
    css: 'linear-gradient(to top, #a8edea 0%, #fed6e3 100%)',
    img: '/img/BREAD.png',
    gifImg: '/gifs/BREAD.gif',
    alt: 'bread king AR instagram filter',
    link: 'https://www.instagram.com/p/CF_rPHFF6mY/',
  },
  {
    name: 'Funguy',
    description: 'description',
    css: 'linear-gradient(to top, #a8edea 0%, #fed6e3 100%)',
    img: '/img/FUNGUY.png',
    gifImg: '/gifs/FUNGUY.gif',
    alt: 'funguy AR instagram filter',
    link: 'https://www.instagram.com/ar/594800398099002/',
  },
  {
    name: 'GLAM',
    description: 'description',
    css: 'linear-gradient(to top, #a8edea 0%, #fed6e3 100%)',
    img: '/img/GLAM.png',
    gifImg: '/gifs/GLAM.gif',
    alt: 'glam makeup AR instagram filter',
    link: 'https://www.instagram.com/ar/1606179623103957/'
  },
  {
    name: 'Make it rain',
    description: 'description',
    css: 'linear-gradient(to top, #a8edea 0%, #fed6e3 100%)',
    img: '/img/MAKE_IT_RAIN.png',
    gifImg: '/gifs/MAKE_IT_RAIN.gif',
    alt: 'make it rain money headdress AR instagram filter',
    link: 'https://www.instagram.com/ar/714404519345034/',
  },
  {
    name: 'Cyberglam with Allan Gregorio',
    description: 'description',
    css: 'linear-gradient(to top, #a8edea 0%, #fed6e3 100%)',
    img: '/img/CYBERGLAM.png',
    gifImg: '/gifs/CYBERGLAM.gif',
    alt: 'cyberglam AR instagram filter',
    link: 'https://www.instagram.com/ar/210570973953229/',
  },
  {
    name: 'Kandinsky Audio',
    description: 'description',
    css: 'linear-gradient(to top, #a8edea 0%, #fed6e3 100%)',
    img: '/img/KANDINSKY_TARGET.png',
    gifImg: '/gifs/KANDINSKY_TARGET.gif',
    alt: 'kandinsky audio AR instagram filter',
    link: 'https://www.instagram.com/ar/278595273270608/',
  },
  {
    name: 'Schwartzkopf',
    description: 'description',
    css: 'linear-gradient(to top, #a8edea 0%, #fed6e3 100%)',
    img: '/img/SCHWARTZKOPF.png',
    gifImg: '/gifs/SCHWARTZKOPF.gif',
    alt: 'schwartzkopf AR instagram filter',
    link: '/',
  },
  {
    name: 'Hanami',
    description: 'description',
    css: 'linear-gradient(to top, #a8edea 0%, #fed6e3 100%)',
    img: '/img/Hanami.png',
    gifImg: '/gifs/Hanami.gif',
    alt: 'hanami cherry blossom AR instagram filter',
    link: 'https://www.instagram.com/ar/197333448086515/',
  },
  {
    name: 'Guru',
    description: 'Guru Energydrink celebrates their new Yerba Mate flavor with this interactive AR headpiece!',
    css: 'linear-gradient(to top, #a8edea 0%, #fed6e3 100%)',
    img: '/img/GURU.png',
    gifImg: '/gifs/GURU.gif',
    alt: 'guru energy drink headdress AR instagram filter',
    link: 'https://www.instagram.com/ar/2734230016836203/',
  },
  {
    name: 'FL.ORAL',
    description: '💝 Izzy the bot with my FL.ORAL effect 💖',
    css: 'linear-gradient(to top, #a8edea 0%, #fed6e3 100%)',
    img: '/img/FLORAL.png',
    gifImg: '/gifs/FLORAL.gif',
    alt: 'floral instagram filter',
    link: 'https://www.instagram.com/p/CIFttbIguGa/',
  },
  {
    name: 'Goddess',
    description: 'WHO IS SHE? 💙💚💙 \n 💎🔫🧊🍏💦🐢🦋🦎🐬🍀💧🌿❄️🥦💠🌱🐳☘️ \n I made a little update to this effect. It always reminds me of the Dutch Master painter from my hometown Hiëronymus Bosch. \n You can find this effect on my profile under the >🙂< icon!',
    css: 'linear-gradient(to top, #a8edea 0%, #96fbc4 100%)',
    img: '/img/GOD_DESS.png',
    gifImg: '/gifs/GOD_DESS.gif',
    alt: 'Goddess instagram filter',
    link: 'https://www.instagram.com/ar/1024062211319175/',
  },
  {
    name: 'Carmen Miranda',
    description: '🍏🍎🍐🍊🍋🍌🍉🍇🍓🍈🥥🍍🥭🍑🍒🥝',
    css: 'linear-gradient(to top, #96fbc4 0%, #f9f586 100%)',
    img: '/img/CarmenMiranda.png',
    gifImg: '/gifs/CarmenMiranda.gif',
    alt: 'Carmen Miranda headdress instagram filter',
    link: 'https://www.instagram.com/ar/288598838777550/',
  },
  {
    name: 'Valentines Bimba Y Lola',
    description: 'description',
    css: 'linear-gradient(to top, #a8edea 0%, #fed6e3 100%)',
    img: '/img/Valentines_Bimba.png',
    gifImg: '/gifs/Valentines_Bimba.gif',
    alt: 'Valentines Bimba Y Lola instagram filter',
    link: 'https://www.instagram.com/p/CKvn_WWlVsE/?utm_source=ig_web_copy_link',
  },
  {
    name: 'Pumpkin Spice',
    description: "OMG! It’s Sweater Weather you guys! 🤎🧣🍂🧥☕️🧶🌂🕷🍄🧦🍊🥾🍁☔️✨.",
    css: 'linear-gradient(120deg, #f6d365 0%, #fda085 100%)',
    img: '/img/Pumpkin_Spice.png',
    gifImg: '/gifs/Pumpkin_Spice.gif',
    alt: 'Pumpkin Spice headdress AR instagram filter',
    link: 'https://www.instagram.com/ar/665697990735929/',
  },
  {
    name: 'Swampify',
    description: "December 2020 is all about #DigitalArtMonth Miami! From the 7th of December through the 7th of January you can grab your phone 📱, a friend 🤗 and a mask and discover amazing digital artworks throughout Miami! 🔥💥🌟💫⚡️💝 \n My Snapchat LIDAR based effect SWAMPIFY is on display too. 🦆🌾✨ \n Can you spot the 🐸? \n Presented by @cadaf_art \n Check out the website to see the most amazing digital artists on the block!",
    css: 'linear-gradient(to top, #5ee7df 0%, #0d8567 100%)',
    img: '/img/Swampify.png',
    gifImg: '/gifs/Swampify.gif',
    alt: 'swampify Snapchat world effect AR filter',
    link: 'https://lens.snapchat.com/85e6b7f15db2422b8aff98520de807ea',
  },
]
